# Generated by Django 4.0.2 on 2023-01-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bufferRad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addy_text', models.CharField(max_length=200, verbose_name='Place of Interest')),
            ],
        ),
        migrations.RemoveField(
            model_name='userradius',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='userradius',
            name='uRadius_text',
            field=models.BigIntegerField(default=2),
        ),
    ]
