# Generated by Django 4.0.2 on 2023-01-20 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bufferRad', '0002_addy_remove_userradius_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addy',
            name='object_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userradius',
            name='uRadius_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bufferRad.addy'),
        ),
    ]
